version: 2
updates:
- package-ecosystem: docker
  directory: "/jupyter"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - 3.9.2.pre.buster
    - 3.9.3.pre.buster
